version: '3.7'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8081:8081"
    environment:     
      SPRING_PROFILES_ACTIVE: local
  eureka-client-app1:
    build: ./eureka-client-app1
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka    
  eureka-client-app2:
    build: ./eureka-client-app2
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka     
  
