spring:
  application:    
    name: ${eureka.app.name:eurekaserver}


server: 
  port: ${eureka.server.port:8081}


eureka:
  instance:   
    hostname: ${eureka.server.hostname:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    


